### ISSUE TITLE
Issues with Scene and Anchor Samples

### ISSUE THREAD

**Issue by eswaranand1997** [oculus-samples/Unity-StarterSamples#3] opened 2023-12-30 00:10 UTC
Ran into issues with the Unity-Discover reference project that are related to some of the starter samples. Mentioned it here: https://github.com/oculus-samples/Unity-Discover/issues/11

With Starter Samples, trying to run SceneManager or Bouncing ball via Link in Editor fails. Scene manager just loads passthrough with no volumes. Bouncing ball similarly shows no volumes and balls simply drop out to infinity. 

With the SpatialAnchor sample, i am able to create and save an anchor (although saving does throw a warning in console, but the green save icon appears). Trying to load anchors afterwards fails. This is the error that shows up:

<img width="974" alt="image" src="https://github.com/oculus-samples/Unity-StarterSamples/assets/78716202/684d0052-e950-4482-877e-ecda22c1ccf8">

**Comment by tdmowrer** [comment] 2024-01-11 01:37
> With the SpatialAnchor sample, i am able to create and save an anchor (although saving does throw a warning in console, but the green save icon appears). Trying to load anchors afterwards fails.

The exception is slightly misleading; it is unable to get a pose for the anchor (for some unknown reason), and the assumption is that the only reason this would happen is if the anchor wasn't yet localized. That sample only tries to get the pose after the anchor is localized, so it is failing for some other reason.

However, I wasn't able to reproduce this.

Is this still accurate? (from https://github.com/oculus-samples/Unity-Discover/issues/11#issue-2060469359)

> testing on Quest Pro over Link and Quest 2.
Link App version: Oculus App Version 60.0.0.162.352 (60.0.0.162.352)
Headset Version: 60.0.0.193.366.548441753

Does it happen on both Quest Pro and Quest 2?

**Comment by chettilaura** [comment] 2024-01-16 06:51
![Screenshot 2024-01-16 194507](https://github.com/oculus-samples/Unity-StarterSamples/assets/114359471/04894362-d8d6-4c5b-85ba-6b6e0c4872c2)

We also have the same problem with the SpatialAnchor scene in the StarterSamples project testing on quest3 through link.

The process we followed was:
1. enter create mode
2. press A to create anchor
3. exit create mode
4. point on the created anchor and press A to load the UI on the anchor
5. pull trigger to save the anchor
6. stop running the unity scene
7. rerun the unity scene
8. switch the UI to Load Local anchors and pull trigger
9. Then the issue pop up on the unity console


We also tested the same project on another desktop which worked fine without this error.

**Comment by eswaranand1997** [comment] 2024-01-16 21:48
> Does it happen on both Quest Pro and Quest 2?

This was tested on Quest Pro over link. And yes, it still does happen to me. I will try another desktop I have and see if that makes any difference.

**Comment by Spphire** [comment] 2024-02-03 09:01
Quest3 over link does work for me, but after building the apk on quest3, it doesn't work. #7 
Do u know the reason?




> > With the SpatialAnchor sample, i am able to create and save an anchor (although saving does throw a warning in console, but the green save icon appears). Trying to load anchors afterwards fails.
> 
> The exception is slightly misleading; it is unable to get a pose for the anchor (for some unknown reason), and the assumption is that the only reason this would happen is if the anchor wasn't yet localized. That sample only tries to get the pose after the anchor is localized, so it is failing for some other reason.
> 
> However, I wasn't able to reproduce this.
> 
> Is this still accurate? (from [oculus-samples/Unity-Discover#11 (comment)](https://github.com/oculus-samples/Unity-Discover/issues/11#issue-2060469359))
> 
> > testing on Quest Pro over Link and Quest 2.
> > Link App version: Oculus App Version 60.0.0.162.352 (60.0.0.162.352)
> > Headset Version: 60.0.0.193.366.548441753
> 
> Does it happen on both Quest Pro and Quest 2?



> ![Screenshot 2024-01-16 194507](https://private-user-images.githubusercontent.com/114359471/296955395-04894362-d8d6-4c5b-85ba-6b6e0c4872c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTA5ODcsIm5iZiI6MTcwNjk1MDY4NywicGF0aCI6Ii8xMTQzNTk0NzEvMjk2OTU1Mzk1LTA0ODk0MzYyLWQ4ZDYtNGM1Yi04NWJhLTZiNmUwYzQ4NzJjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwODU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmQzNTY4OTY1NjVkZjU1NjEyNGJiYzkwMzY2YWQ0MGQyOWVkMzAxZDJkNDYxYTM1ZDNlMjgzMGU4NzU3MTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G3z8LuO0YCUD10p8igV7eL5Muz53q8L8nC-Kw4csguw)
> 
> We also have the same problem with the SpatialAnchor scene in the StarterSamples project testing on quest3 through link.
> 
> The process we followed was:
> 
> 1. enter create mode
> 2. press A to create anchor
> 3. exit create mode
> 4. point on the created anchor and press A to load the UI on the anchor
> 5. pull trigger to save the anchor
> 6. stop running the unity scene
> 7. rerun the unity scene
> 8. switch the UI to Load Local anchors and pull trigger
> 9. Then the issue pop up on the unity console
> 
> We also tested the same project on another desktop which worked fine without this error.

**Comment by AlexThiv** [comment] 2024-08-27 21:46
This has been resolved in our latest update. Can you validate if you still encounter this issue?

**Closed** 2024-09-03 22:28 UTC
